// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreinoC_.Context;

#nullable disable

namespace TreinoC_.Migrations
{
    [DbContext(typeof(PwiContext))]
    [Migration("20251120195930_PWI")]
    partial class PWI
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TreinoC_.Entities.Chat", b =>
                {
                    b.Property<int>("Idchat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idchat"));

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Idchat");

                    b.ToTable("Tb_chat");
                });

            modelBuilder.Entity("TreinoC_.Entities.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<bool>("Blativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nmsala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSala");

                    b.ToTable("Tb_salas");
                });

            modelBuilder.Entity("TreinoC_.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Dsmensagem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmNick")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NmSenha")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Tb_usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
